modLoader="javafml"
loaderVersion="[46,48)"
license="GNU General Public License v3.0"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
	modId="commonality"
	version="${file.jarVersion}"
	displayName="Commonality"
	updateJSONURL="https://api.modrinth.com/updates/apexcore/forge_updates.json"
	displayURL="https://github.com/ApexStudios-Dev/Commonality"
	# logo="banner.png"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="Library which houses various common use game elements used throughout various Minecraft Forge Mods."
	displayTest="MATCH_VERSION"

[[dependencies.commonality]]
	modId="forge"
	mandatory=true
	versionRange="[46.0.0,48.0.0)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.commonality]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.20,1.20.2)"
	ordering="AFTER"
	side="BOTH"
