modLoader="javafml"
loaderVersion="[41,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/Commonality/issues"

[[mods]]
	modId="commonality"
	version="${file.jarVersion}"
	displayName="Commonality"
	credits="Apex"
	authors="Apex"
	description="Simple testing mod"

[[dependencies.commonality]]
	modId="forge"
	mandatory=true
	versionRange="[41,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.commonality]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19,1.20)"
	ordering="AFTER"
	side="BOTH"