modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/Commonality/issues"

[[mods]]
	modId="commonality"
	version="${file.jarVersion}"
	displayName="Commonality"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/commonality.json"
	displayURL="https://github.com/ApexStudios-Dev/Commonality"
	# logo="banner.png"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="Library which houses various common use game elements used throughout various Minecraft Forge Mods."
	displayTest="MATCH_VERSION"

[[dependencies.commonality]]
	modId="forge"
	mandatory=true
	versionRange="[40.1.60,41)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.commonality.custom.mc-publish]
		ignore=true
[[dependencies.commonality]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.commonality.custom.mc-publish]
		ignore=true