modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/Commonality/issues"

[[mods]]
	modId="commonality"
	version="${file.jarVersion}"
	displayName="Commonality"
	credits="Apex"
	authors="Apex"
	description="Simple testing mod"

[[dependencies.commonality]]
	modId="forge"
	mandatory=true
	versionRange="[40.1.60,41)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.commonality]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="AFTER"
	side="BOTH"