package xyz.apex.forge.commonality.tags;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.Tags;
import xyz.apex.forge.commonality.Mods;

@SuppressWarnings("ALL")
public interface ItemTags
{
	interface Vanilla
	{
		TagKey<Item> WOOL = net.minecraft.tags.ItemTags.WOOL;
		TagKey<Item> PLANKS = net.minecraft.tags.ItemTags.PLANKS;
		TagKey<Item> STONE_BRICKS = net.minecraft.tags.ItemTags.STONE_BRICKS;
		TagKey<Item> WOODEN_BUTTONS = net.minecraft.tags.ItemTags.WOODEN_BUTTONS;
		TagKey<Item> BUTTONS = net.minecraft.tags.ItemTags.BUTTONS;
		TagKey<Item> WOOL_CARPETS = net.minecraft.tags.ItemTags.WOOL_CARPETS;
		TagKey<Item> WOODEN_DOORS = net.minecraft.tags.ItemTags.WOODEN_DOORS;
		TagKey<Item> WOODEN_STAIRS = net.minecraft.tags.ItemTags.WOODEN_STAIRS;
		TagKey<Item> WOODEN_SLABS = net.minecraft.tags.ItemTags.WOODEN_SLABS;
		TagKey<Item> WOODEN_FENCES = net.minecraft.tags.ItemTags.WOODEN_FENCES;
		TagKey<Item> FENCE_GATES = net.minecraft.tags.ItemTags.FENCE_GATES;
		TagKey<Item> WOODEN_PRESSURE_PLATES = net.minecraft.tags.ItemTags.WOODEN_PRESSURE_PLATES;
		TagKey<Item> WOODEN_TRAPDOORS = net.minecraft.tags.ItemTags.WOODEN_TRAPDOORS;
		TagKey<Item> DOORS = net.minecraft.tags.ItemTags.DOORS;
		TagKey<Item> SAPLINGS = net.minecraft.tags.ItemTags.SAPLINGS;
		TagKey<Item> LOGS_THAT_BURN = net.minecraft.tags.ItemTags.LOGS_THAT_BURN;
		TagKey<Item> LOGS = net.minecraft.tags.ItemTags.LOGS;
		TagKey<Item> DARK_OAK_LOGS = net.minecraft.tags.ItemTags.DARK_OAK_LOGS;
		TagKey<Item> OAK_LOGS = net.minecraft.tags.ItemTags.OAK_LOGS;
		TagKey<Item> BIRCH_LOGS = net.minecraft.tags.ItemTags.BIRCH_LOGS;
		TagKey<Item> ACACIA_LOGS = net.minecraft.tags.ItemTags.ACACIA_LOGS;
		TagKey<Item> CHERRY_LOGS = net.minecraft.tags.ItemTags.CHERRY_LOGS;
		TagKey<Item> JUNGLE_LOGS = net.minecraft.tags.ItemTags.JUNGLE_LOGS;
		TagKey<Item> SPRUCE_LOGS = net.minecraft.tags.ItemTags.SPRUCE_LOGS;
		TagKey<Item> MANGROVE_LOGS = net.minecraft.tags.ItemTags.MANGROVE_LOGS;
		TagKey<Item> CRIMSON_STEMS = net.minecraft.tags.ItemTags.CRIMSON_STEMS;
		TagKey<Item> WARPED_STEMS = net.minecraft.tags.ItemTags.WARPED_STEMS;
		TagKey<Item> BAMBOO_BLOCKS = net.minecraft.tags.ItemTags.BAMBOO_BLOCKS;
		TagKey<Item> WART_BLOCKS = net.minecraft.tags.ItemTags.WART_BLOCKS;
		TagKey<Item> BANNERS = net.minecraft.tags.ItemTags.BANNERS;
		TagKey<Item> SAND = net.minecraft.tags.ItemTags.SAND;
		TagKey<Item> SMELTS_TO_GLASS = net.minecraft.tags.ItemTags.SMELTS_TO_GLASS;
		TagKey<Item> STAIRS = net.minecraft.tags.ItemTags.STAIRS;
		TagKey<Item> SLABS = net.minecraft.tags.ItemTags.SLABS;
		TagKey<Item> WALLS = net.minecraft.tags.ItemTags.WALLS;
		TagKey<Item> ANVIL = net.minecraft.tags.ItemTags.ANVIL;
		TagKey<Item> RAILS = net.minecraft.tags.ItemTags.RAILS;
		TagKey<Item> LEAVES = net.minecraft.tags.ItemTags.LEAVES;
		TagKey<Item> TRAPDOORS = net.minecraft.tags.ItemTags.TRAPDOORS;
		TagKey<Item> SMALL_FLOWERS = net.minecraft.tags.ItemTags.SMALL_FLOWERS;
		TagKey<Item> BEDS = net.minecraft.tags.ItemTags.BEDS;
		TagKey<Item> FENCES = net.minecraft.tags.ItemTags.FENCES;
		TagKey<Item> TALL_FLOWERS = net.minecraft.tags.ItemTags.TALL_FLOWERS;
		TagKey<Item> FLOWERS = net.minecraft.tags.ItemTags.FLOWERS;
		TagKey<Item> PIGLIN_REPELLENTS = net.minecraft.tags.ItemTags.PIGLIN_REPELLENTS;
		TagKey<Item> PIGLIN_LOVED = net.minecraft.tags.ItemTags.PIGLIN_LOVED;
		TagKey<Item> IGNORED_BY_PIGLIN_BABIES = net.minecraft.tags.ItemTags.IGNORED_BY_PIGLIN_BABIES;
		TagKey<Item> PIGLIN_FOOD = net.minecraft.tags.ItemTags.PIGLIN_FOOD;
		TagKey<Item> FOX_FOOD = net.minecraft.tags.ItemTags.FOX_FOOD;
		TagKey<Item> GOLD_ORES = net.minecraft.tags.ItemTags.GOLD_ORES;
		TagKey<Item> IRON_ORES = net.minecraft.tags.ItemTags.IRON_ORES;
		TagKey<Item> DIAMOND_ORES = net.minecraft.tags.ItemTags.DIAMOND_ORES;
		TagKey<Item> REDSTONE_ORES = net.minecraft.tags.ItemTags.REDSTONE_ORES;
		TagKey<Item> LAPIS_ORES = net.minecraft.tags.ItemTags.LAPIS_ORES;
		TagKey<Item> COAL_ORES = net.minecraft.tags.ItemTags.COAL_ORES;
		TagKey<Item> EMERALD_ORES = net.minecraft.tags.ItemTags.EMERALD_ORES;
		TagKey<Item> COPPER_ORES = net.minecraft.tags.ItemTags.COPPER_ORES;
		TagKey<Item> NON_FLAMMABLE_WOOD = net.minecraft.tags.ItemTags.NON_FLAMMABLE_WOOD;
		TagKey<Item> SOUL_FIRE_BASE_BLOCKS = net.minecraft.tags.ItemTags.SOUL_FIRE_BASE_BLOCKS;
		TagKey<Item> CANDLES = net.minecraft.tags.ItemTags.CANDLES;
		TagKey<Item> DIRT = net.minecraft.tags.ItemTags.DIRT;
		TagKey<Item> TERRACOTTA = net.minecraft.tags.ItemTags.TERRACOTTA;
		TagKey<Item> COMPLETES_FIND_TREE_TUTORIAL = net.minecraft.tags.ItemTags.COMPLETES_FIND_TREE_TUTORIAL;
		TagKey<Item> BOATS = net.minecraft.tags.ItemTags.BOATS;
		TagKey<Item> CHEST_BOATS = net.minecraft.tags.ItemTags.CHEST_BOATS;
		TagKey<Item> FISHES = net.minecraft.tags.ItemTags.FISHES;
		TagKey<Item> SIGNS = net.minecraft.tags.ItemTags.SIGNS;
		TagKey<Item> MUSIC_DISCS = net.minecraft.tags.ItemTags.MUSIC_DISCS;
		TagKey<Item> CREEPER_DROP_MUSIC_DISCS = net.minecraft.tags.ItemTags.CREEPER_DROP_MUSIC_DISCS;
		TagKey<Item> COALS = net.minecraft.tags.ItemTags.COALS;
		TagKey<Item> ARROWS = net.minecraft.tags.ItemTags.ARROWS;
		TagKey<Item> LECTERN_BOOKS = net.minecraft.tags.ItemTags.LECTERN_BOOKS;
		TagKey<Item> BOOKSHELF_BOOKS = net.minecraft.tags.ItemTags.BOOKSHELF_BOOKS;
		TagKey<Item> BEACON_PAYMENT_ITEMS = net.minecraft.tags.ItemTags.BEACON_PAYMENT_ITEMS;
		TagKey<Item> STONE_TOOL_MATERIALS = net.minecraft.tags.ItemTags.STONE_TOOL_MATERIALS;
		TagKey<Item> STONE_CRAFTING_MATERIALS = net.minecraft.tags.ItemTags.STONE_CRAFTING_MATERIALS;
		TagKey<Item> FREEZE_IMMUNE_WEARABLES = net.minecraft.tags.ItemTags.FREEZE_IMMUNE_WEARABLES;
		TagKey<Item> AXOLOTL_TEMPT_ITEMS = net.minecraft.tags.ItemTags.AXOLOTL_TEMPT_ITEMS;
		TagKey<Item> DAMPENS_VIBRATIONS = net.minecraft.tags.ItemTags.DAMPENS_VIBRATIONS;
		TagKey<Item> CLUSTER_MAX_HARVESTABLES = net.minecraft.tags.ItemTags.CLUSTER_MAX_HARVESTABLES;
		TagKey<Item> COMPASSES = net.minecraft.tags.ItemTags.COMPASSES;
		TagKey<Item> HANGING_SIGNS = net.minecraft.tags.ItemTags.HANGING_SIGNS;
		TagKey<Item> CREEPER_IGNITERS = net.minecraft.tags.ItemTags.CREEPER_IGNITERS;
		TagKey<Item> NOTE_BLOCK_TOP_INSTRUMENTS = net.minecraft.tags.ItemTags.NOTE_BLOCK_TOP_INSTRUMENTS;
		TagKey<Item> TRIMMABLE_ARMOR = net.minecraft.tags.ItemTags.TRIMMABLE_ARMOR;
		TagKey<Item> TRIM_MATERIALS = net.minecraft.tags.ItemTags.TRIM_MATERIALS;
		TagKey<Item> TRIM_TEMPLATES = net.minecraft.tags.ItemTags.TRIM_TEMPLATES;
		TagKey<Item> SNIFFER_FOOD = net.minecraft.tags.ItemTags.SNIFFER_FOOD;
		TagKey<Item> DECORATED_POT_SHARDS = net.minecraft.tags.ItemTags.DECORATED_POT_SHARDS;
		TagKey<Item> SWORDS = net.minecraft.tags.ItemTags.SWORDS;
		TagKey<Item> AXES = net.minecraft.tags.ItemTags.AXES;
		TagKey<Item> HOES = net.minecraft.tags.ItemTags.HOES;
		TagKey<Item> PICKAXES = net.minecraft.tags.ItemTags.PICKAXES;
		TagKey<Item> SHOVELS = net.minecraft.tags.ItemTags.SHOVELS;
		TagKey<Item> TOOLS = net.minecraft.tags.ItemTags.TOOLS;
		TagKey<Item> BREAKS_DECORATED_POTS = net.minecraft.tags.ItemTags.BREAKS_DECORATED_POTS;
	}

	interface Forge
	{
		TagKey<Item> BARRELS = Tags.Items.BARRELS;
		TagKey<Item> BARRELS_WOODEN = Tags.Items.BARRELS_WOODEN;
		TagKey<Item> BONES = Tags.Items.BONES;
		TagKey<Item> BOOKSHELVES = Tags.Items.BOOKSHELVES;
		TagKey<Item> CHESTS = Tags.Items.CHESTS;
		TagKey<Item> CHESTS_ENDER = Tags.Items.CHESTS_ENDER;
		TagKey<Item> CHESTS_TRAPPED = Tags.Items.CHESTS_TRAPPED;
		TagKey<Item> CHESTS_WOODEN = Tags.Items.CHESTS_WOODEN;
		TagKey<Item> COBBLESTONE = Tags.Items.COBBLESTONE;
		TagKey<Item> COBBLESTONE_NORMAL = Tags.Items.COBBLESTONE_NORMAL;
		TagKey<Item> COBBLESTONE_INFESTED = Tags.Items.COBBLESTONE_INFESTED;
		TagKey<Item> COBBLESTONE_MOSSY = Tags.Items.COBBLESTONE_MOSSY;
		TagKey<Item> COBBLESTONE_DEEPSLATE = Tags.Items.COBBLESTONE_DEEPSLATE;
		TagKey<Item> CROPS = Tags.Items.CROPS;
		TagKey<Item> CROPS_BEETROOT = Tags.Items.CROPS_BEETROOT;
		TagKey<Item> CROPS_CARROT = Tags.Items.CROPS_CARROT;
		TagKey<Item> CROPS_NETHER_WART = Tags.Items.CROPS_NETHER_WART;
		TagKey<Item> CROPS_POTATO = Tags.Items.CROPS_POTATO;
		TagKey<Item> CROPS_WHEAT = Tags.Items.CROPS_WHEAT;
		TagKey<Item> DUSTS = Tags.Items.DUSTS;
		TagKey<Item> DUSTS_PRISMARINE = Tags.Items.DUSTS_PRISMARINE;
		TagKey<Item> DUSTS_REDSTONE = Tags.Items.DUSTS_REDSTONE;
		TagKey<Item> DUSTS_GLOWSTONE = Tags.Items.DUSTS_GLOWSTONE;
		TagKey<Item> DYES = Tags.Items.DYES;
		TagKey<Item> DYES_BLACK = Tags.Items.DYES_BLACK;
		TagKey<Item> DYES_RED = Tags.Items.DYES_RED;
		TagKey<Item> DYES_GREEN = Tags.Items.DYES_GREEN;
		TagKey<Item> DYES_BROWN = Tags.Items.DYES_BROWN;
		TagKey<Item> DYES_BLUE = Tags.Items.DYES_BLUE;
		TagKey<Item> DYES_PURPLE = Tags.Items.DYES_PURPLE;
		TagKey<Item> DYES_CYAN = Tags.Items.DYES_CYAN;
		TagKey<Item> DYES_LIGHT_GRAY = Tags.Items.DYES_LIGHT_GRAY;
		TagKey<Item> DYES_GRAY = Tags.Items.DYES_GRAY;
		TagKey<Item> DYES_PINK = Tags.Items.DYES_PINK;
		TagKey<Item> DYES_LIME = Tags.Items.DYES_LIME;
		TagKey<Item> DYES_YELLOW = Tags.Items.DYES_YELLOW;
		TagKey<Item> DYES_LIGHT_BLUE = Tags.Items.DYES_LIGHT_BLUE;
		TagKey<Item> DYES_MAGENTA = Tags.Items.DYES_MAGENTA;
		TagKey<Item> DYES_ORANGE = Tags.Items.DYES_ORANGE;
		TagKey<Item> DYES_WHITE = Tags.Items.DYES_WHITE;
		TagKey<Item> EGGS = Tags.Items.EGGS;
		TagKey<Item> ENCHANTING_FUELS = Tags.Items.ENCHANTING_FUELS;
		TagKey<Item> END_STONES = Tags.Items.END_STONES;
		TagKey<Item> ENDER_PEARLS = Tags.Items.ENDER_PEARLS;
		TagKey<Item> FEATHERS = Tags.Items.FEATHERS;
		TagKey<Item> FENCE_GATES = Tags.Items.FENCE_GATES;
		TagKey<Item> FENCE_GATES_WOODEN = Tags.Items.FENCE_GATES_WOODEN;
		TagKey<Item> FENCES = Tags.Items.FENCES;
		TagKey<Item> FENCES_NETHER_BRICK = Tags.Items.FENCES_NETHER_BRICK;
		TagKey<Item> FENCES_WOODEN = Tags.Items.FENCES_WOODEN;
		TagKey<Item> GEMS = Tags.Items.GEMS;
		TagKey<Item> GEMS_DIAMOND = Tags.Items.GEMS_DIAMOND;
		TagKey<Item> GEMS_EMERALD = Tags.Items.GEMS_EMERALD;
		TagKey<Item> GEMS_AMETHYST = Tags.Items.GEMS_AMETHYST;
		TagKey<Item> GEMS_LAPIS = Tags.Items.GEMS_LAPIS;
		TagKey<Item> GEMS_PRISMARINE = Tags.Items.GEMS_PRISMARINE;
		TagKey<Item> GEMS_QUARTZ = Tags.Items.GEMS_QUARTZ;
		TagKey<Item> GLASS = Tags.Items.GLASS;
		TagKey<Item> GLASS_BLACK = Tags.Items.GLASS_BLACK;
		TagKey<Item> GLASS_BLUE = Tags.Items.GLASS_BLUE;
		TagKey<Item> GLASS_BROWN = Tags.Items.GLASS_BROWN;
		TagKey<Item> GLASS_COLORLESS = Tags.Items.GLASS_COLORLESS;
		TagKey<Item> GLASS_CYAN = Tags.Items.GLASS_CYAN;
		TagKey<Item> GLASS_GRAY = Tags.Items.GLASS_GRAY;
		TagKey<Item> GLASS_GREEN = Tags.Items.GLASS_GREEN;
		TagKey<Item> GLASS_LIGHT_BLUE = Tags.Items.GLASS_LIGHT_BLUE;
		TagKey<Item> GLASS_LIGHT_GRAY = Tags.Items.GLASS_LIGHT_GRAY;
		TagKey<Item> GLASS_LIME = Tags.Items.GLASS_LIME;
		TagKey<Item> GLASS_MAGENTA = Tags.Items.GLASS_MAGENTA;
		TagKey<Item> GLASS_ORANGE = Tags.Items.GLASS_ORANGE;
		TagKey<Item> GLASS_PINK = Tags.Items.GLASS_PINK;
		TagKey<Item> GLASS_PURPLE = Tags.Items.GLASS_PURPLE;
		TagKey<Item> GLASS_RED = Tags.Items.GLASS_RED;
		TagKey<Item> GLASS_SILICA = Tags.Items.GLASS_SILICA;
		TagKey<Item> GLASS_TINTED = Tags.Items.GLASS_TINTED;
		TagKey<Item> GLASS_WHITE = Tags.Items.GLASS_WHITE;
		TagKey<Item> GLASS_YELLOW = Tags.Items.GLASS_YELLOW;
		TagKey<Item> GLASS_PANES = Tags.Items.GLASS_PANES;
		TagKey<Item> GLASS_PANES_BLACK = Tags.Items.GLASS_PANES_BLACK;
		TagKey<Item> GLASS_PANES_BLUE = Tags.Items.GLASS_PANES_BLUE;
		TagKey<Item> GLASS_PANES_BROWN = Tags.Items.GLASS_PANES_BROWN;
		TagKey<Item> GLASS_PANES_COLORLESS = Tags.Items.GLASS_PANES_COLORLESS;
		TagKey<Item> GLASS_PANES_CYAN = Tags.Items.GLASS_PANES_CYAN;
		TagKey<Item> GLASS_PANES_GRAY = Tags.Items.GLASS_PANES_GRAY;
		TagKey<Item> GLASS_PANES_GREEN = Tags.Items.GLASS_PANES_GREEN;
		TagKey<Item> GLASS_PANES_LIGHT_BLUE = Tags.Items.GLASS_PANES_LIGHT_BLUE;
		TagKey<Item> GLASS_PANES_LIGHT_GRAY = Tags.Items.GLASS_PANES_LIGHT_GRAY;
		TagKey<Item> GLASS_PANES_LIME = Tags.Items.GLASS_PANES_LIME;
		TagKey<Item> GLASS_PANES_MAGENTA = Tags.Items.GLASS_PANES_MAGENTA;
		TagKey<Item> GLASS_PANES_ORANGE = Tags.Items.GLASS_PANES_ORANGE;
		TagKey<Item> GLASS_PANES_PINK = Tags.Items.GLASS_PANES_PINK;
		TagKey<Item> GLASS_PANES_PURPLE = Tags.Items.GLASS_PANES_PURPLE;
		TagKey<Item> GLASS_PANES_RED = Tags.Items.GLASS_PANES_RED;
		TagKey<Item> GLASS_PANES_WHITE = Tags.Items.GLASS_PANES_WHITE;
		TagKey<Item> GLASS_PANES_YELLOW = Tags.Items.GLASS_PANES_YELLOW;
		TagKey<Item> GRAVEL = Tags.Items.GRAVEL;
		TagKey<Item> GUNPOWDER = Tags.Items.GUNPOWDER;
		TagKey<Item> HEADS = Tags.Items.HEADS;
		TagKey<Item> INGOTS = Tags.Items.INGOTS;
		TagKey<Item> INGOTS_BRICK = Tags.Items.INGOTS_BRICK;
		TagKey<Item> INGOTS_COPPER = Tags.Items.INGOTS_COPPER;
		TagKey<Item> INGOTS_GOLD = Tags.Items.INGOTS_GOLD;
		TagKey<Item> INGOTS_IRON = Tags.Items.INGOTS_IRON;
		TagKey<Item> INGOTS_NETHERITE = Tags.Items.INGOTS_NETHERITE;
		TagKey<Item> INGOTS_NETHER_BRICK = Tags.Items.INGOTS_NETHER_BRICK;
		TagKey<Item> LEATHER = Tags.Items.LEATHER;
		TagKey<Item> MUSHROOMS = Tags.Items.MUSHROOMS;
		TagKey<Item> NETHER_STARS = Tags.Items.NETHER_STARS;
		TagKey<Item> NETHERRACK = Tags.Items.NETHERRACK;
		TagKey<Item> NUGGETS = Tags.Items.NUGGETS;
		TagKey<Item> NUGGETS_GOLD = Tags.Items.NUGGETS_GOLD;
		TagKey<Item> NUGGETS_IRON = Tags.Items.NUGGETS_IRON;
		TagKey<Item> OBSIDIAN = Tags.Items.OBSIDIAN;
		TagKey<Item> ORE_BEARING_GROUND_DEEPSLATE = Tags.Items.ORE_BEARING_GROUND_DEEPSLATE;
		TagKey<Item> ORE_BEARING_GROUND_NETHERRACK = Tags.Items.ORE_BEARING_GROUND_NETHERRACK;
		TagKey<Item> ORE_BEARING_GROUND_STONE = Tags.Items.ORE_BEARING_GROUND_STONE;
		TagKey<Item> ORE_RATES_DENSE = Tags.Items.ORE_RATES_DENSE;
		TagKey<Item> ORE_RATES_SINGULAR = Tags.Items.ORE_RATES_SINGULAR;
		TagKey<Item> ORE_RATES_SPARSE = Tags.Items.ORE_RATES_SPARSE;
		TagKey<Item> ORES = Tags.Items.ORES;
		TagKey<Item> ORES_COAL = Tags.Items.ORES_COAL;
		TagKey<Item> ORES_COPPER = Tags.Items.ORES_COPPER;
		TagKey<Item> ORES_DIAMOND = Tags.Items.ORES_DIAMOND;
		TagKey<Item> ORES_EMERALD = Tags.Items.ORES_EMERALD;
		TagKey<Item> ORES_GOLD = Tags.Items.ORES_GOLD;
		TagKey<Item> ORES_IRON = Tags.Items.ORES_IRON;
		TagKey<Item> ORES_LAPIS = Tags.Items.ORES_LAPIS;
		TagKey<Item> ORES_NETHERITE_SCRAP = Tags.Items.ORES_NETHERITE_SCRAP;
		TagKey<Item> ORES_QUARTZ = Tags.Items.ORES_QUARTZ;
		TagKey<Item> ORES_REDSTONE = Tags.Items.ORES_REDSTONE;
		TagKey<Item> ORES_IN_GROUND_DEEPSLATE = Tags.Items.ORES_IN_GROUND_DEEPSLATE;
		TagKey<Item> ORES_IN_GROUND_NETHERRACK = Tags.Items.ORES_IN_GROUND_NETHERRACK;
		TagKey<Item> ORES_IN_GROUND_STONE = Tags.Items.ORES_IN_GROUND_STONE;
		TagKey<Item> RAW_MATERIALS = Tags.Items.RAW_MATERIALS;
		TagKey<Item> RAW_MATERIALS_COPPER = Tags.Items.RAW_MATERIALS_COPPER;
		TagKey<Item> RAW_MATERIALS_GOLD = Tags.Items.RAW_MATERIALS_GOLD;
		TagKey<Item> RAW_MATERIALS_IRON = Tags.Items.RAW_MATERIALS_IRON;
		TagKey<Item> RODS = Tags.Items.RODS;
		TagKey<Item> RODS_BLAZE = Tags.Items.RODS_BLAZE;
		TagKey<Item> RODS_WOODEN = Tags.Items.RODS_WOODEN;
		TagKey<Item> SAND = Tags.Items.SAND;
		TagKey<Item> SAND_COLORLESS = Tags.Items.SAND_COLORLESS;
		TagKey<Item> SAND_RED = Tags.Items.SAND_RED;
		TagKey<Item> SANDSTONE = Tags.Items.SANDSTONE;
		TagKey<Item> SEEDS = Tags.Items.SEEDS;
		TagKey<Item> SEEDS_BEETROOT = Tags.Items.SEEDS_BEETROOT;
		TagKey<Item> SEEDS_MELON = Tags.Items.SEEDS_MELON;
		TagKey<Item> SEEDS_PUMPKIN = Tags.Items.SEEDS_PUMPKIN;
		TagKey<Item> SEEDS_WHEAT = Tags.Items.SEEDS_WHEAT;
		TagKey<Item> SHEARS = Tags.Items.SHEARS;
		TagKey<Item> SLIMEBALLS = Tags.Items.SLIMEBALLS;
		TagKey<Item> STAINED_GLASS = Tags.Items.STAINED_GLASS;
		TagKey<Item> STAINED_GLASS_PANES = Tags.Items.STAINED_GLASS_PANES;
		TagKey<Item> STONE = Tags.Items.STONE;
		TagKey<Item> STORAGE_BLOCKS = Tags.Items.STORAGE_BLOCKS;
		TagKey<Item> STORAGE_BLOCKS_AMETHYST = Tags.Items.STORAGE_BLOCKS_AMETHYST;
		TagKey<Item> STORAGE_BLOCKS_COAL = Tags.Items.STORAGE_BLOCKS_COAL;
		TagKey<Item> STORAGE_BLOCKS_COPPER = Tags.Items.STORAGE_BLOCKS_COPPER;
		TagKey<Item> STORAGE_BLOCKS_DIAMOND = Tags.Items.STORAGE_BLOCKS_DIAMOND;
		TagKey<Item> STORAGE_BLOCKS_EMERALD = Tags.Items.STORAGE_BLOCKS_EMERALD;
		TagKey<Item> STORAGE_BLOCKS_GOLD = Tags.Items.STORAGE_BLOCKS_GOLD;
		TagKey<Item> STORAGE_BLOCKS_IRON = Tags.Items.STORAGE_BLOCKS_IRON;
		TagKey<Item> STORAGE_BLOCKS_LAPIS = Tags.Items.STORAGE_BLOCKS_LAPIS;
		TagKey<Item> STORAGE_BLOCKS_NETHERITE = Tags.Items.STORAGE_BLOCKS_NETHERITE;
		TagKey<Item> STORAGE_BLOCKS_QUARTZ = Tags.Items.STORAGE_BLOCKS_QUARTZ;
		TagKey<Item> STORAGE_BLOCKS_RAW_COPPER = Tags.Items.STORAGE_BLOCKS_RAW_COPPER;
		TagKey<Item> STORAGE_BLOCKS_RAW_GOLD = Tags.Items.STORAGE_BLOCKS_RAW_GOLD;
		TagKey<Item> STORAGE_BLOCKS_RAW_IRON = Tags.Items.STORAGE_BLOCKS_RAW_IRON;
		TagKey<Item> STORAGE_BLOCKS_REDSTONE = Tags.Items.STORAGE_BLOCKS_REDSTONE;
		TagKey<Item> STRING = Tags.Items.STRING;
		TagKey<Item> TOOLS = Tags.Items.TOOLS;
		TagKey<Item> TOOLS_SWORDS = Tags.Items.TOOLS_SWORDS;
		TagKey<Item> TOOLS_AXES = Tags.Items.TOOLS_AXES;
		TagKey<Item> TOOLS_PICKAXES = Tags.Items.TOOLS_PICKAXES;
		TagKey<Item> TOOLS_SHOVELS = Tags.Items.TOOLS_SHOVELS;
		TagKey<Item> TOOLS_HOES = Tags.Items.TOOLS_HOES;
		TagKey<Item> TOOLS_SHIELDS = Tags.Items.TOOLS_SHIELDS;
		TagKey<Item> TOOLS_BOWS = Tags.Items.TOOLS_BOWS;
		TagKey<Item> TOOLS_CROSSBOWS = Tags.Items.TOOLS_CROSSBOWS;
		TagKey<Item> TOOLS_FISHING_RODS = Tags.Items.TOOLS_FISHING_RODS;
		TagKey<Item> TOOLS_TRIDENTS = Tags.Items.TOOLS_TRIDENTS;
		TagKey<Item> ARMORS = Tags.Items.ARMORS;
		TagKey<Item> ARMORS_HELMETS = Tags.Items.ARMORS_HELMETS;
		TagKey<Item> ARMORS_CHESTPLATES = Tags.Items.ARMORS_CHESTPLATES;
		TagKey<Item> ARMORS_LEGGINGS = Tags.Items.ARMORS_LEGGINGS;
		TagKey<Item> ARMORS_BOOTS = Tags.Items.ARMORS_BOOTS;
	}

	interface Common
	{
		TagKey<Item> QUARTZ_ORES = vanillaTag("quartz_ores");

		TagKey<Item> TOOLS_WRENCH = forgeTag("tools/wrench");
	}

	static TagKey<Item> tag(String namespace, String path)
	{
		return TagKey.create(Registries.ITEM, new ResourceLocation(namespace, path));
	}

	static TagKey<Item> forgeTag(String path)
	{
		return tag(Mods.FORGE, path);
	}

	static TagKey<Item> vanillaTag(String path)
	{
		return tag(Mods.MINECRAFT, path);
	}
}
